apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: composer-boring-v1-pvc
  namespace: tradingbot22
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: composer-boring-v1
  namespace: tradingbot22
spec:
  schedule: "32 3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: composer-boring-v1
            image: guestros/tradingbot22-bot:composer-boring-v1
            imagePullPolicy: Always
            volumeMounts:
              - mountPath: /app/persistent/
                name: composer-boring-v1-pv
          volumes:
            - name: composer-boring-v1-pv
              persistentVolumeClaim:
                claimName: composer-boring-v1-pvc
          restartPolicy: OnFailure