# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: composer-oppy-volhedge-pvc
#   namespace: tradingbot22
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Mi
# ---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: composer-oppy-volhedge
  namespace: tradingbot22
spec:
  schedule: "25 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: composer-oppy-volhedge
            image: guestros/tradingbot22-bot:composer-oppy-v1
            imagePullPolicy: Always
            env:
              - name: "MODE"
                value: "volhedge"
          #   volumeMounts:
          #     - mountPath: /app/persistent/
          #       name: composer-oppy-volhedge-pv
          # volumes:
          #   - name: composer-oppy-volhedge-pv
          #     persistentVolumeClaim:
          #       claimName: composer-oppy-volhedge-pvc
          restartPolicy: OnFailure