# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: earnings-calendar-bot-v1-pvc
#   namespace: tradingbot22
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 500Mi
# ---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: earnings-calendar-bot-v1
  namespace: tradingbot22
spec:
  schedule: "30 5 * * *" # every day 5:30
  # schedule: "* * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tradingbot22-earnings-calendar-bot-v1
            image: guestros/tradingbot22-bot:earnings-calendar-effect-v1
            imagePullPolicy: Always
            env:
            - name: BACKENDURL
              value: "http://tradingbot-baseimage-service:8000"
          restartPolicy: OnFailure