# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: eiten-longonly-daily-weeklyrebalance-pvc
#   namespace: tradingbot22
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 500Mi
# ---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: eiten-longonly-daily-weeklyrebalance
  namespace: tradingbot22
spec:
  schedule: "30 16 * * 3" # weekly on wednesday
  # schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tradingbot22-eiten-longonly-daily-weeklyrebalance
            image: guestros/tradingbot22-bot:eiten_v1
            imagePullPolicy: Always
            env:
            - name: BACKENDURL
              value: "http://tradingbot-baseimage-service:8000"
          restartPolicy: OnFailure