apiVersion: batch/v1
kind: CronJob
metadata:
  name: tradingbot22-lightgbm-bot-aapl
  namespace: tradingbot22
spec:
  schedule: "1 16 * * *"
  # schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tradingbot22-rsi-bot-aapl
            image: guestros/tradingbot22-bot:lightgbm
            imagePullPolicy: Always
            env:
            - name: TICKER
              value: "AAPL"
            # command:
            # - /bin/sh
            # - -c
            # - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure