# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: simplesma-v1-pvc
#   namespace: tradingbot22
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Mi
# ---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: simplesma-v1
  namespace: tradingbot22
spec:
  schedule: "35 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: simplesma-v1
            image: guestros/tradingbot22-bot:simplesma-v1
            imagePullPolicy: Always
            # env:
            #   - name: "MODE"
            #     value: "volhedge"
          #   volumeMounts:
          #     - mountPath: /app/persistent/
          #       name: simplesma-v1-pv
          # volumes:
          #   - name: simplesma-v1-pv
          #     persistentVolumeClaim:
          #       claimName: simplesma-v1-pvc
          restartPolicy: OnFailure